# Generated by Django 4.2.2 on 2025-03-29 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student_profiles',
        ),
    ]
