# Generated by Django 4.2.2 on 2025-04-26 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_resume_link_student_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='applied_companies',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='student',
            name='availability_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='certifications',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 26, 8, 2, 41, 870358, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='languages_known',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='student',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='portfolio_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_company_type',
            field=models.CharField(choices=[('Startup', 'Startup'), ('MNC', 'MNC'), ('Any', 'Any')], default='MNC', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_job_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='projects',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='student',
            name='relocation_ready',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='tenth_board',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='tenth_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='twelfth_board',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='twelfth_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year_of_graduation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
