# Generated by Django 4.2.2 on 2025-04-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_achievements_student_applied_companies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
