# Generated by Django 4.2.2 on 2025-04-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='offers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='student',
            name='placement_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='student',
            name='placement_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Placed', 'Placed')], default='Pending', max_length=50),
        ),
    ]
