# Generated by Django 4.2.2 on 2025-04-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_offers_student_placement_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='contact',
        ),
    ]
