# Generated by Django 5.1.7 on 2025-04-16 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
        ('students', '0002_alter_student_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='location',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='time',
        ),
        migrations.AddField(
            model_name='interview',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Selected', 'Selected')], default='Scheduled', max_length=50),
        ),
        migrations.AlterField(
            model_name='interview',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='students.student'),
        ),
        migrations.AlterModelTable(
            name='interview',
            table='interview_schedules',
        ),
    ]
