# Generated by Django 4.2.2 on 2025-04-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_delete_event_remove_interview_student_delete_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdrive',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Past', 'Past')], default='Upcoming', max_length=20),
        ),
    ]
