# Generated by Django 4.2.2 on 2025-04-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_placementdrive_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdrive',
            name='ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
